### ISSUE TITLE
Create initial version of the Assimilation Nanoprobe in Rust.

### ISSUE THREAD

**Issue by Alan-R** [Alan-R/rust-nanoprobe#1]
# Create new version of Assimilation Nanoprobe in Rust.

## Tasks

- [ ] https://github.com/Alan-R/rust-nanoprobe/issues/2
- [ ] https://github.com/Alan-R/rust-nanoprobe/issues/3
- [ ] https://github.com/Alan-R/rust-nanoprobe/issues/4

**Comment by Alan-R** [comment]
I've started my journey learning Rust with a little "hello world" command execution code which I will evolve into the real code. So far, understanding how to deal with Rust object lifetime has been my difficulty - as expected.
